# Generated by Django 6.0.6 on 2026-06-17 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('pengarang', models.CharField(max_length=100)),
                ('kategori', models.CharField(default='Novel', max_length=50)),
                ('penerbit', models.CharField(max_length=100)),
                ('tahun_terbit', models.IntegerField()),
                ('isbn', models.CharField(max_length=50)),
                ('rak_lokasi', models.CharField(max_length=50)),
                ('stok', models.IntegerField(default=0)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kelas', models.CharField(max_length=50)),
                ('nis', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Nonaktif', 'Nonaktif')], default='Aktif', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateField()),
                ('tanggal_jatuh_tempo', models.DateField()),
                ('keperluan', models.CharField(default='Bacaan pribadi', max_length=100)),
                ('petugas', models.CharField(default='Budi Siregar', max_length=100)),
                ('status', models.CharField(choices=[('Dipinjam', 'Dipinjam'), ('Sudah Dikembalikan', 'Sudah Dikembalikan')], default='Dipinjam', max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.buku')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.siswa')),
            ],
        ),
    ]
