# Generated by Django 6.0.6 on 2026-06-18 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=150)),
                ('pengarang', models.CharField(max_length=100)),
                ('stok', models.IntegerField(default=0)),
                ('tahun_terbit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'buku',
            },
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id_peminjam', models.AutoField(primary_key=True, serialize=False)),
                ('nama_peminjam', models.CharField(max_length=100)),
                ('id_buku', models.ForeignKey(db_column='id_buku', on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.buku')),
            ],
            options={
                'db_table': 'peminjam',
            },
        ),
    ]
