# Generated by Django 6.0.6 on 2026-06-17 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peminjaman',
            name='siswa',
        ),
        migrations.RemoveField(
            model_name='buku',
            name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='buku',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='buku',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='buku',
            name='penerbit',
        ),
        migrations.RemoveField(
            model_name='buku',
            name='rak_lokasi',
        ),
        migrations.RemoveField(
            model_name='peminjaman',
            name='buku',
        ),
        migrations.RemoveField(
            model_name='peminjaman',
            name='catatan',
        ),
        migrations.RemoveField(
            model_name='peminjaman',
            name='id',
        ),
        migrations.RemoveField(
            model_name='peminjaman',
            name='keperluan',
        ),
        migrations.RemoveField(
            model_name='peminjaman',
            name='petugas',
        ),
        migrations.RemoveField(
            model_name='peminjaman',
            name='status',
        ),
        migrations.RemoveField(
            model_name='peminjaman',
            name='tanggal_jatuh_tempo',
        ),
        migrations.RemoveField(
            model_name='peminjaman',
            name='tanggal_pinjam',
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='id_buku',
            field=models.ForeignKey(db_column='id_buku', default=1, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.buku'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='id_peminjam',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='nama_peminjam',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buku',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='buku',
            name='judul',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='buku',
            name='tahun_terbit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='buku',
            table='buku',
        ),
        migrations.AlterModelTable(
            name='peminjaman',
            table='peminjam',
        ),
        migrations.DeleteModel(
            name='Siswa',
        ),
    ]
